# Generated by Django 4.0.5 on 2022-07-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RyansMusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
