# Generated by Django 4.0.5 on 2022-07-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RyansMusic', '0003_artist_alter_album_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
