# Generated by Django 4.0.5 on 2022-07-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RyansMusic', '0004_alter_album_artist_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
