# Generated by Django 4.0.5 on 2022-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RyansMusic', '0005_alter_album_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist_list',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
