# Generated by Django 4.0.5 on 2022-07-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RyansMusic', '0008_album_favorite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='RyansMusic.album'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
